[package]
name = "x12-host"
version.workspace = true
edition.workspace = true
description = "Host application for parsing large X12 files"

[dependencies]
thiserror = "2"

parser = { path = "../parser" }
x12-validation = { path = "../validation" }

[[bin]]
name = "x12"
path = "src/main.rs"
